### ISSUE TITLE
Inline CSS

### ISSUE THREAD

**Issue by szepeviktor** [barrykooij/what-the-file#7]
https://github.com/barrykooij/what-the-file/blob/master/what-the-file.php#L293

Please consider `wp_add_inline_style( 'wp-admin', $css_string );`

**Comment by barrykooij** [comment]
We'll stick with inline CSS because it's only added for administrators.

**Comment by szepeviktor** [comment]
Excuse me, maybe I was unclear. 
Threre is no contradiction. 
My suggestion above is also inline&admin only.
